# name: Send Issue to Discord

# on:
#   issues:
#     types: [opened]

# jobs:
#   discord:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Send Discord Notification
#         run: |
#           curl -H "Content-Type: application/json" \
#             -X POST \
#             -d "{
#               \"embeds\": [{
#                 \"title\": \"ğŸ”” New Issue Created!\",
#                 \"url\": \"${{ github.event.issue.html_url }}\",
#                 \"color\": 15258703,
#                 \"description\": \"#${{ github.event.issue.number }} - ${{ github.event.issue.title }}\",
#                 \"fields\": [
#                   {
#                     \"name\": \"ğŸ‘¤ ì‘ì„±ì\",
#                     \"value\": \"${{ github.event.issue.user.login }}\",
#                     \"inline\": true
#                   },
#                   {
#                     \"name\": \"ğŸ“ ë‚´ìš©\",
#                     \"value\": \"${{ github.event.issue.body || 'ë‚´ìš© ì—†ìŒ' }}\"
#                   }
#                 ],
#                 \"timestamp\": \"${{ github.event.issue.created_at }}\"
#               }]
#             }" \
#             ${{ secrets.DISCORD_WEBHOOK_ISSUES }}
